dbt_project:
  outputs:
    dev:
      type: clickhouse
      host: clickhouse
      port: 8123
      user: admin
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      schema: crypto_db
  target: dev
